<a href="https://colab.research.google.com/github/piyushprog19/Data_Analysis/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#NumPy is a Python library, was created in 2005 by Travis Oliphant
#NumPy is used for working with arrays. NumPy is short for “Numerical Python”. 50× faster than traditional Python lists.

In [ ]:
#importing numpy library
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [ ]:
# To create a ndarray, we can pass a list, tuple or other array like object

In [ ]:
#create 2DArray
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)
#Find dimension of array
print(arr2.ndim)

[[1 2 3]
 [4 5 6]]
2


In [ ]:
#Numpy array indexing
arr3 = np.array([1, 4, 6, 4, 3])
print(arr3[3])

4


In [ ]:
#Slicing negative indexing
print(arr3[0 : 3])
print(arr3[-1])
print(arr3[-2 : -1])

[1 4 6]
3
[4]


In [ ]:
#get 3rd value and 4th value and add them
arr4 = np.array([1, 2, 3, 4])
print(arr[2] + arr[3])


7


In [ ]:
#Access the element on the first row, second column
arr5 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr5)
print("2nd element in first row",arr5[0, 1])


[[1 2 3 4]
 [5 6 7 8]]
2nd element in first row 2


In [ ]:
#Access the element on 2nd row, 3rd column
arr6 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr6[1, 2])

7


In [ ]:
#3D array
arr7 = np.array([[[1, 2, 3],[4, 5, 6]]])
print(arr7[0, 1, 2])

6


In [ ]:
#Negative indexing
arr8 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr8[1, -1])

8


In [ ]:
#Slicing Array
arr9 = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr9[1:5])
print(arr9[4:])
print(arr9[:4])
print(arr9[-3:-1])
print(arr9[1:5:2])
print(arr9[::2])

[2 3 4 5]
[5 6 7]
[1 2 3 4]
[5 6]
[2 4]
[1 3 5 7]


In [ ]:
#Slicing in 2d array
#from the 2nd element, slice elements fro idx 1 o idx 4
arr10 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr10[1, 1:4])
print(arr10[0:2, 2])
print(arr10[0:2, 1:4])

[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


# Datatypes in numpy
#i- integer
#b- boolean
#u- unsigned integer
#f- float
#c- complex float
#m- timedelta
#M- dateTime
#O- Object
#S- String

In [ ]:
#creating an array with data type string:
import numpy as np
arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)
print(arr.dtype)


[b'1' b'2' b'3' b'4']
|S1


In [ ]:
#Change data type from float to integer
import numpy as np
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [ ]:
#Make a copy, change the original array, and display both arrays:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [ ]:
#Numpy array shape
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)

(2, 4)


In [ ]:
#reshaping
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
#Flattening the array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
newarr = arr.reshape(-1)
print(newarr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
#Numpy array iterating
arr = np.array([1, 2, 3])
for x in arr:
  print(x)

1
2
3
