<a href="https://colab.research.google.com/github/piyushprog19/Data_Analysis/blob/Practice/Practice_Questions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# 1. Array properties
arr = np.array([10, 20, 30, 40, 50])
print(arr)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[10 20 30 40 50]
(5,)
5
int64


In [ ]:
import numpy as np
# 2. 3 x 4 array
arr2 = np.arange(1, 13).reshape(3, 4)
print(arr2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
import numpy as np
# 3. Zeros, Ones, Identity
print(np.zeros(5))
print(np.ones(5))
print(np.eye(3))

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
import numpy as np
# 4. Even numbers
print(np.arange(10, 51, 2))


[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [ ]:

# 5. 10 equally spaced numbers
print(np.linspace(0, 1, 10))

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


Array Arithmetic


In [ ]:
import numpy as np

# 6
a = np.array([10, 20, 30, 40])
b = np.array([2, 4, 5, 8])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)


Addition: [12 24 35 48]
Subtraction: [ 8 16 25 32]
Multiplication: [ 20  80 150 320]
Division: [5. 5. 6. 5.]


In [ ]:
import numpy as np

# 7
arr = np.array([1, 2, 3, 4, 5])

print("Square:", arr ** 2)
print("Cube:", arr ** 3)


Square: [ 1  4  9 16 25]
Cube: [  1   8  27  64 125]


In [ ]:
import numpy as np

# 8
arr = np.array([100, 200, 300, 400])
print("After 15% increase:", arr * 1.15)


After 15% increase: [115. 230. 345. 460.]


In [ ]:
import numpy as np

# 9
a = np.array([10, 25, 30, 45])
b = np.array([15, 20, 35, 40])

print("Maximum:", np.maximum(a, b))
print("Minimum:", np.minimum(a, b))

Maximum: [15 25 35 45]
Minimum: [10 20 30 40]


Indexing And Slicing


In [13]:
import numpy as np
arr = np.arange(21)
print("Array:", arr)
print("First five:", arr[:5])
print("Last five:", arr[-5:])
print("Index 5 to 15:", arr[5:16])
print("Every second:", arr[::2])

Array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
First five: [0 1 2 3 4]
Last five: [16 17 18 19 20]
Index 5 to 15: [ 5  6  7  8  9 10 11 12 13 14 15]
Every second: [ 0  2  4  6  8 10 12 14 16 18 20]


In [17]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr[:5] = 100
print(arr)

[100 100 100 100 100   6   7   8   9  10]


In [16]:

arr = np.array([10, 20, 30, 40, 50])
view = arr[1:4]
view[0] = 100
print("Original array:", arr)
print("View:", view)

Original array: [ 10 100  30  40  50]
View: [100  30  40]


In [15]:
arr = np.array([10, 20, 30, 40, 50])
reverse = arr[::-1]
print(reverse)

[50 40 30 20 10]


2D Array Indexing and Slicing

In [18]:
import numpy as np

arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]])
print("Second row:", arr[1])
print("Third column:", arr[:, 2])
print("Element 50:", arr[1, 1])


Second row: [40 50 60]
Third column: [30 60 90]
Element 50: 50


In [19]:
sub = arr[0:2, 1:3]
print(sub)

[[20 30]
 [50 60]]


In [20]:
arr = np.arange(1, 26).reshape(5, 5)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


Reshaping And Transpose


In [21]:
import numpy as np
arr = np.arange(1, 13)
matrix = arr.reshape(3, 4)
print(matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [23]:
arr = np.arange(1, 11)
matrix = arr.reshape(2, 5)
print(matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [24]:
arr = np.arange(1, 13).reshape(3, 4)
print("Original:")
print(arr)

Original:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [25]:
arr = np.arange(1, 25).reshape(2, 3, 4)
print("Original shape:", arr.shape)
print(arr)

Original shape: (2, 3, 4)
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
